POST /questionbanks/addquestion/NodeJs/Taushiq HTTP/1.1
Content-Type: application/json
Host: localhost:3000
# POST http://localhost:3000/questionbanks/addquestionbank
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImZpcnN0bmFtZSI6IlZpbm9kIiwibGFzdG5hbWUiOiJLdW1hciIsImlhdCI6MTU5NjEyNTU3ODQzNn0.TrzBen8dkXtNMsaY0LpSaFe7Icu3LjcSgm6H8hMxewA

{ "question": "Hello", "answer_one" : "" , "answer_two" : "" ,"answer_three" : "" ,"answer_four" : "" ,"correct_answer" : 2  } 

